#############################################################################
# Makefile for building: RMOverTest
# Generated by qmake (2.01a) (Qt 4.8.7) on: Sun Apr 11 09:27:09 2021
# Project:  RMOverTest.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile RMOverTest.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -m64 -pipe -g -Wall -W $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++0x -D_GLIBCXX_USE_CXX11_ABI=0 -g -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/opt/GALAXY -I/opt/DahuaTech/DependsInclude/Include -I/opt/DahuaTech/DependsInclude/Depends
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS)   /usr/local/lib/libopencv_imgproc.so /usr/local/lib/libopencv_highgui.so /usr/local/lib/libopencv_core.so /usr/local/lib/libopencv_imgcodecs.so /usr/local/lib/libopencv_video.so /usr/local/lib/libopencv_videoio.so /usr/local/lib/libopencv_calib3d.so /usr/local/lib/libopencv_ml.so /usr/lib/x86_64-linux-gnu/libpthread.so -L/opt/DahuaTech/DependsInclude/Depends/ -lImageConvert -lMVSDK -L/opt/GALAXY/ -lgxiapi -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = serialPort/serialPort.cpp \
		coordinateTransform/coordinateTransform.cpp \
		targetModel/robot.cpp \
		targetModel/buff.cpp \
		targetModel/targetModel.cpp \
		targetModel/criticalcore.cpp \
		videoSource/camera.cpp \
		main.cpp \
		tool/tool.cpp \
		videoSource/videoSource.cpp \
		tool/kalman.cpp \
		controller.cpp \
		tool/triplebuffering.cpp \
		serialPort/pmbcbspkeeper.cpp \
		trajectoryCalculation.cpp \
		videoSource/galaxycamera.cpp 
OBJECTS       = serialPort.o \
		coordinateTransform.o \
		robot.o \
		buff.o \
		targetModel.o \
		criticalcore.o \
		camera.o \
		main.o \
		tool.o \
		videoSource.o \
		kalman.o \
		controller.o \
		triplebuffering.o \
		pmbcbspkeeper.o \
		trajectoryCalculation.o \
		galaxycamera.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		RMOverTest.pro
QMAKE_TARGET  = RMOverTest
DESTDIR       = 
TARGET        = RMOverTest

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9][^0-9]*\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: RMOverTest.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile RMOverTest.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile RMOverTest.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/RMOverTest1.0.0 || $(MKDIR) .tmp/RMOverTest1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/RMOverTest1.0.0/ && (cd `dirname .tmp/RMOverTest1.0.0` && $(TAR) RMOverTest1.0.0.tar RMOverTest1.0.0 && $(COMPRESS) RMOverTest1.0.0.tar) && $(MOVE) `dirname .tmp/RMOverTest1.0.0`/RMOverTest1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/RMOverTest1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

serialPort.o: serialPort/serialPort.cpp serialPort/serialPort.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serialPort.o serialPort/serialPort.cpp

coordinateTransform.o: coordinateTransform/coordinateTransform.cpp coordinateTransform/coordinateTransform.h \
		videoSource/videoSource.h \
		videoSource/camera.h \
		tool/triplebuffering.h \
		videoSource/galaxycamera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o coordinateTransform.o coordinateTransform/coordinateTransform.cpp

robot.o: targetModel/robot.cpp targetModel/robot.h \
		targetModel/targetModel.h \
		videoSource/videoSource.h \
		videoSource/camera.h \
		tool/triplebuffering.h \
		videoSource/galaxycamera.h \
		serialPort/pmbcbspkeeper.h \
		serialPort/serialPort.h \
		preferences.h \
		coordinateTransform/coordinateTransform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o robot.o targetModel/robot.cpp

buff.o: targetModel/buff.cpp targetModel/buff.h \
		tool/tool.h \
		targetModel/targetModel.h \
		videoSource/videoSource.h \
		videoSource/camera.h \
		tool/triplebuffering.h \
		videoSource/galaxycamera.h \
		serialPort/pmbcbspkeeper.h \
		serialPort/serialPort.h \
		preferences.h \
		trajectoryCalculation.h \
		coordinateTransform/coordinateTransform.h \
		targetModel/criticalcore.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o buff.o targetModel/buff.cpp

targetModel.o: targetModel/targetModel.cpp targetModel/targetModel.h \
		videoSource/videoSource.h \
		videoSource/camera.h \
		tool/triplebuffering.h \
		videoSource/galaxycamera.h \
		serialPort/pmbcbspkeeper.h \
		serialPort/serialPort.h \
		preferences.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o targetModel.o targetModel/targetModel.cpp

criticalcore.o: targetModel/criticalcore.cpp targetModel/criticalcore.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o criticalcore.o targetModel/criticalcore.cpp

camera.o: videoSource/camera.cpp videoSource/camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camera.o videoSource/camera.cpp

main.o: main.cpp preferences.h \
		targetModel/buff.h \
		tool/tool.h \
		targetModel/targetModel.h \
		videoSource/videoSource.h \
		videoSource/camera.h \
		tool/triplebuffering.h \
		videoSource/galaxycamera.h \
		serialPort/pmbcbspkeeper.h \
		serialPort/serialPort.h \
		trajectoryCalculation.h \
		coordinateTransform/coordinateTransform.h \
		targetModel/criticalcore.h \
		targetModel/robot.h \
		controller.h \
		tool/kalman.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

tool.o: tool/tool.cpp tool/tool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tool.o tool/tool.cpp

videoSource.o: videoSource/videoSource.cpp videoSource/videoSource.h \
		videoSource/camera.h \
		tool/triplebuffering.h \
		videoSource/galaxycamera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o videoSource.o videoSource/videoSource.cpp

kalman.o: tool/kalman.cpp tool/kalman.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kalman.o tool/kalman.cpp

controller.o: controller.cpp controller.h \
		videoSource/videoSource.h \
		videoSource/camera.h \
		tool/triplebuffering.h \
		videoSource/galaxycamera.h \
		serialPort/pmbcbspkeeper.h \
		serialPort/serialPort.h \
		preferences.h \
		coordinateTransform/coordinateTransform.h \
		targetModel/buff.h \
		tool/tool.h \
		targetModel/targetModel.h \
		trajectoryCalculation.h \
		targetModel/criticalcore.h \
		targetModel/robot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o controller.o controller.cpp

triplebuffering.o: tool/triplebuffering.cpp serialPort/pmbcbspkeeper.h \
		serialPort/serialPort.h \
		tool/triplebuffering.h \
		preferences.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o triplebuffering.o tool/triplebuffering.cpp

pmbcbspkeeper.o: serialPort/pmbcbspkeeper.cpp serialPort/pmbcbspkeeper.h \
		serialPort/serialPort.h \
		tool/triplebuffering.h \
		preferences.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pmbcbspkeeper.o serialPort/pmbcbspkeeper.cpp

trajectoryCalculation.o: trajectoryCalculation.cpp trajectoryCalculation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o trajectoryCalculation.o trajectoryCalculation.cpp

galaxycamera.o: videoSource/galaxycamera.cpp videoSource/galaxycamera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o galaxycamera.o videoSource/galaxycamera.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

